apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-api
  namespace: envforge-platform
  labels:
    app.kubernetes.io/name: control-api
    app.kubernetes.io/part-of: envforge
automountServiceAccountToken: true
