apiVersion: v1
kind: Service
metadata:
  name: reliability-demo-api
  namespace: env-reliability-demo
  labels:
    app: reliability-demo-api
    app.kubernetes.io/managed-by: envforge
    envforge.io/environment: reliability-demo
spec:
  selector:
    app: reliability-demo-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
