spring.application.name=reliability-demo-api
server.port=8080

app.version=${APP_VERSION:0.1.0}
app.force-not-ready=${FORCE_NOT_READY:false}

# Prometheus scraping
management.endpoints.web.exposure.include=prometheus
