apiVersion: v1
kind: Secret
metadata:
  name: control-api-db
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: control-api
    {{- include "envforge-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.controlApi.env.dbPassword | quote }}
