apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: portal
    {{- include "envforge-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.portal.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: portal
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portal
        {{- include "envforge-platform.labels" . | nindent 8 }}
    spec:
      serviceAccountName: portal
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: portal
          image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag }}"
          imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
