environment:
  name: helm-demo-m1
  owner: bogdan
  template: static-web
  expiresAt: "2026-08-02T18:00:00Z"

quota:
  enabled: true
  requests:
    cpu: "500m"
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
  objectCounts:
    pods: 5
    services: 3
    configMaps: 5
    secrets: 5

limitRange:
  enabled: true
  container:
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 250m
      memory: 256Mi
    min:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: 500m
      memory: 512Mi