apiVersion: v1
kind: Service
metadata:
  name: reliability-demo-api-metrics
  namespace: env-reliability-demo
  labels:
    app: reliability-demo-api
    app.kubernetes.io/managed-by: envforge
    envforge.io/environment: reliability-demo
    envforge.io/monitoring: "true"
spec:
  selector:
    app: reliability-demo-api
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reliability-demo-api
  namespace: env-reliability-demo
  labels:
    app.kubernetes.io/managed-by: envforge
    envforge.io/environment: reliability-demo
    envforge.io/component: monitoring
spec:
  selector:
    matchLabels:
      envforge.io/monitoring: "true"

  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 5s
